# Generated by Django 4.1.7 on 2023-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="start_date",
        ),
    ]
