# Generated by Django 4.1.7 on 2023-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_remove_offer_end_date_remove_offer_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
