# Generated by Django 4.1.7 on 2023-04-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
