# Generated by Django 4.1.7 on 2023-04-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0008_remove_userprofile_country_remove_userprofile_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="second_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
