# Generated by Django 4.1.7 on 2023-04-03 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_userprofile_first_name_userprofile_second_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
