# Generated by Django 4.1.7 on 2023-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_rename_second_name_userprofile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_name",
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name="account",
            name="second_name",
            field=models.CharField(default=True, max_length=20),
        ),
    ]
