# Generated by Django 4.1.7 on 2023-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_account_first_name_account_second_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="account",
            name="second_name",
            field=models.CharField(max_length=20),
        ),
    ]
