# Generated by Django 4.1.7 on 2023-04-04 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_account_first_name_alter_account_second_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="zip_code",
        ),
    ]
