# Generated by Django 4.1.7 on 2023-04-04 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_address_name_remove_address_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
    ]
