# Generated by Django 4.1.7 on 2023-04-04 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_remove_address_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
    ]
