# Generated by Django 4.1.7 on 2023-04-05 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line_2",
        ),
    ]
