# Generated by Django 4.1.7 on 2023-04-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(default=99999999999, max_length=12),
        ),
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
