# Generated by Django 4.1.7 on 2023-04-12 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_address_name_address_phone_address_zip_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="zip_code",
            new_name="Pincode",
        ),
    ]
