# Generated by Django 4.1.7 on 2023-04-27 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_address_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
