# Generated by Django 4.1.7 on 2023-05-01 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_rename_second_name_account_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="Pincode",
            new_name="pincode",
        ),
    ]
