# Generated by Django 4.1.7 on 2023-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_variation"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
