# Generated by Django 4.1.7 on 2023-04-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_variation"),
        ("cart", "0004_remove_cartitem_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="size",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
