# Generated by Django 4.1.7 on 2023-04-06 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_cartitem_user_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="variation",
            new_name="variations",
        ),
    ]
