# Generated by Django 4.1.7 on 2023-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_phone_alter_order_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(default=False, max_length=6),
        ),
    ]
