# Generated by Django 4.1.7 on 2023-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=10)),
                ("min_amount", models.CharField(max_length=10, null=True)),
                ("active_date", models.DateField(null=True)),
                ("expire_date", models.DateField(null=True)),
                ("discount_amount", models.CharField(default=100, max_length=10)),
            ],
        ),
    ]
